openapi: 3.0.0
info:
  title: Saasuga API Specifications
  description: Free and Open Source URL Shortener
  contact:
    name: Ahmad Irsyadul Ibad
    url: 'https://irsyadulibad.my.id'
    email: ahmadirsyadulibad7@gmail.com
  version: 0.0.1
  license:
    name: MIT
    url: 'https://github.com/Degovan/saasuga-backend/blob/main/LICENSE'
servers:
  - url: 'https://backend.saasu.ga/api'
    description: Production Server
    variables: {}
  - url: 'https://backend-dev.saasu.ga/api'
    description: Development Server
paths:
  '/login/{provider}':
    get:
      summary: Redirect for Login to Social Account
      tags:
        - Auth
      responses:
        '200':
          description: Success Login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSchema'
              example:
                meta:
                  code: 200
                  status: success
                  message: Success getting redirect url
                data:
                  redirect_url: >-
                    https://accounts.google.com/o/oauth2/auth?scope=openid+profile+email&response_type=code
      parameters:
        - name: provider
          required: true
          in: path
          schema:
            type: string
            enum:
              - google
              - github
    post:
      summary: Get Logged in Account
      description: ''
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum:
              - google
              - github
        - name: code
          in: query
          required: true
          schema:
            type: string
      operationId: ''
      responses:
        default:
          description: Default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSchema'
              example:
                meta:
                  code: 200
                  status: success
                  message: Login successfully
                data:
                  user:
                    name: User
                    email: email@example.com
                  access_token: 12345678
      tags:
        - Auth
  '/login/{provider}/code':
    get:
      summary: Get Social Account Token Code
      tags:
        - Auth
      responses:
        '200':
          description: Success get code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSchema'
              example:
                meta:
                  code: 200
                  status: success
                  message:
                data:
                  code: abcdexdjsakfsagsagasx123341412
                  provider: google
      parameters:
        - name: provider
          required: true
          in: path
          schema:
            type: string
            enum:
              - google
              - github
  '/urls':
    get:
      summary: ''
      description: Get all user's ShortURL
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSchema'
              example:
                meta:
                  code: 200
                  status: success
                  message: null
                data:
                  urls:
                    - id: 11
                      title: Saasuga Shortener
                      destination: https://saasu.ga
                      keyword: saasuga
                      expiration: 622936665
      tags:
        - Url
    post:
      summary: ''
      description: Create new ShortURL
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSchema'
              example:
                meta:
                  code: 200
                  status: success
                  message: Success add new url
                data:
                  id: 11
                  title: Saasuga Shortener
                  destination: https://saasu.ga
                  keyword: saasuga
                  expiration: 622936665
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                  required: true
                title:
                  type: string
                keyword:
                  type: string
            example:
              title: Saasuga Shortener
              destination: https://saasu.ga
              keyword: saasuga
      tags:
        - Url
  'urls/{id}':
    put:
      summary: ''
      description: Edit the user's URL
      security:
        - BearerAuth: []
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: int
      responses:
        '204':
          description: Success Response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                destination:
                  type: string
                  required: true
                title:
                  type: string
                keyword:
                  type: string
            example:
              title: Google Web Address
              destination: https://google.com
              keyword: google-short
      tags:
        - Url
    delete:
      summary: ''
      description: Delete the user's URL
      security:
        - BearerAuth: []
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: int
      responses:
        '204':
          description: Success Response
      tags:
        - Url
components:
  links: {}
  callbacks: {}
  schemas:
    ResponseSchema:
      type: object
      properties:
        meta:
          type: object
          properties:
            code:
              type: integer
              format: int32
            status:
              type: string
            message:
              type: string
        data:
          type: object
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Bearer token for authenticated user
tags: []
